// Code generated by xsdgen. DO NOT EDIT.

package grantData

// Must match the pattern none|[0-9]{1,15}
type AwardCeilingType string

// Must match the pattern [0-9]{1,15}
type AwardFloorType string

// Must match the pattern [0-9]{2}[\.][0-9]{3}
type CFDANumberType string

// May be no more than 255 items long
type CategoryExplanationType string

// May be no more than 3 items long
type CostSharingOrMatchingRequirementType string

// May be no more than 18000 items long
type DescriptionType string

// May be no more than 2 items long
type EligibleApplicantTypes string

// Must match the pattern [0-9]*
type EstimatedTotalProgramFundingType string

// Must match the pattern [0-9]*
type ExpectedNumberOfAwardsType string

// Must match the pattern [0-9]*
type FiscalYearType string

// May be no more than 3 items long
type FundingActivityCategoryTypes string

// May be no more than 2 items long
type FundingInstrumentTypes string

// May be no more than 40 items long
type FundingOpportunityNumberType string

// May be no more than 300 items long
type GrantorContactDescriptionType string

type Grants struct {
	OpportunitySynopsisDetail10 []string `xml:"OpportunitySynopsisDetail_1_0,omitempty"`
	OpportunityForecastDetail10 []string `xml:"OpportunityForecastDetail_1_0,omitempty"`
}

// Must match the pattern (0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])\d\d\d\d
type MMDDYYYYType string

// Must match the pattern [0-9]{1,20}
type Number20DigitsType string

// May be no more than 20 items long
type OpportunityCategoryTypes string

type OpportunityForecastDetail10 struct {
	OpportunityID                         Number20DigitsType                   `xml:"OpportunityID"`
	OpportunityTitle                      StringWithoutNewLine255Type          `xml:"OpportunityTitle,omitempty"`
	OpportunityNumber                     FundingOpportunityNumberType         `xml:"OpportunityNumber,omitempty"`
	OpportunityCategory                   OpportunityCategoryTypes             `xml:"OpportunityCategory,omitempty"`
	OpportunityCategoryExplanation        CategoryExplanationType              `xml:"OpportunityCategoryExplanation,omitempty"`
	FundingInstrumentType                 []FundingInstrumentTypes             `xml:"FundingInstrumentType,omitempty"`
	CategoryOfFundingActivity             []FundingActivityCategoryTypes       `xml:"CategoryOfFundingActivity,omitempty"`
	CategoryExplanation                   String2500Type                       `xml:"CategoryExplanation,omitempty"`
	CFDANumbers                           []CFDANumberType                     `xml:"CFDANumbers,omitempty"`
	EligibleApplicants                    []EligibleApplicantTypes             `xml:"EligibleApplicants,omitempty"`
	AdditionalInformationOnEligibility    String4000Type                       `xml:"AdditionalInformationOnEligibility,omitempty"`
	AgencyCode                            StringMin1Max255Type                 `xml:"AgencyCode,omitempty"`
	AgencyName                            StringMin1Max255Type                 `xml:"AgencyName,omitempty"`
	PostDate                              MMDDYYYYType                         `xml:"PostDate,omitempty"`
	LastUpdatedDate                       MMDDYYYYType                         `xml:"LastUpdatedDate,omitempty"`
	EstimatedSynopsisPostDate             MMDDYYYYType                         `xml:"EstimatedSynopsisPostDate,omitempty"`
	FiscalYear                            FiscalYearType                       `xml:"FiscalYear,omitempty"`
	EstimatedSynopsisCloseDate            MMDDYYYYType                         `xml:"EstimatedSynopsisCloseDate,omitempty"`
	EstimatedSynopsisCloseDateExplanation String4000Type                       `xml:"EstimatedSynopsisCloseDateExplanation,omitempty"`
	EstimatedAwardDate                    MMDDYYYYType                         `xml:"EstimatedAwardDate,omitempty"`
	EstimatedProjectStartDate             MMDDYYYYType                         `xml:"EstimatedProjectStartDate,omitempty"`
	AwardCeiling                          AwardCeilingType                     `xml:"AwardCeiling,omitempty"`
	AwardFloor                            AwardFloorType                       `xml:"AwardFloor,omitempty"`
	EstimatedTotalProgramFunding          EstimatedTotalProgramFundingType     `xml:"EstimatedTotalProgramFunding,omitempty"`
	ExpectedNumberOfAwards                ExpectedNumberOfAwardsType           `xml:"ExpectedNumberOfAwards,omitempty"`
	Description                           DescriptionType                      `xml:"Description,omitempty"`
	Version                               String20Type                         `xml:"Version,omitempty"`
	CostSharingOrMatchingRequirement      CostSharingOrMatchingRequirementType `xml:"CostSharingOrMatchingRequirement,omitempty"`
	ArchiveDate                           MMDDYYYYType                         `xml:"ArchiveDate,omitempty"`
	AdditionalInformationURL              String250Type                        `xml:"AdditionalInformationURL,omitempty"`
	AdditionalInformationText             String250Type                        `xml:"AdditionalInformationText,omitempty"`
	GrantorContactEmail                   String130Type                        `xml:"GrantorContactEmail,omitempty"`
	GrantorContactEmailDescription        String102Type                        `xml:"GrantorContactEmailDescription,omitempty"`
	GrantorContactName                    String2500Type                       `xml:"GrantorContactName,omitempty"`
	GrantorContactPhoneNumber             String100Type                        `xml:"GrantorContactPhoneNumber,omitempty"`
}

type OpportunitySynopsisDetail10 struct {
	OpportunityID                      Number20DigitsType                   `xml:"OpportunityID"`
	OpportunityTitle                   StringWithoutNewLine255Type          `xml:"OpportunityTitle,omitempty"`
	OpportunityNumber                  FundingOpportunityNumberType         `xml:"OpportunityNumber,omitempty"`
	OpportunityCategory                OpportunityCategoryTypes             `xml:"OpportunityCategory,omitempty"`
	OpportunityCategoryExplanation     CategoryExplanationType              `xml:"OpportunityCategoryExplanation,omitempty"`
	FundingInstrumentType              []FundingInstrumentTypes             `xml:"FundingInstrumentType,omitempty"`
	CategoryOfFundingActivity          []FundingActivityCategoryTypes       `xml:"CategoryOfFundingActivity,omitempty"`
	CategoryExplanation                String2500Type                       `xml:"CategoryExplanation,omitempty"`
	CFDANumbers                        []CFDANumberType                     `xml:"CFDANumbers,omitempty"`
	EligibleApplicants                 []EligibleApplicantTypes             `xml:"EligibleApplicants,omitempty"`
	AdditionalInformationOnEligibility String4000Type                       `xml:"AdditionalInformationOnEligibility,omitempty"`
	AgencyCode                         StringMin1Max255Type                 `xml:"AgencyCode,omitempty"`
	AgencyName                         StringMin1Max255Type                 `xml:"AgencyName,omitempty"`
	PostDate                           MMDDYYYYType                         `xml:"PostDate,omitempty"`
	CloseDate                          MMDDYYYYType                         `xml:"CloseDate,omitempty"`
	CloseDateExplanation               String4000Type                       `xml:"CloseDateExplanation,omitempty"`
	LastUpdatedDate                    MMDDYYYYType                         `xml:"LastUpdatedDate"`
	AwardCeiling                       AwardCeilingType                     `xml:"AwardCeiling,omitempty"`
	AwardFloor                         AwardFloorType                       `xml:"AwardFloor,omitempty"`
	EstimatedTotalProgramFunding       EstimatedTotalProgramFundingType     `xml:"EstimatedTotalProgramFunding,omitempty"`
	ExpectedNumberOfAwards             ExpectedNumberOfAwardsType           `xml:"ExpectedNumberOfAwards,omitempty"`
	Description                        DescriptionType                      `xml:"Description,omitempty"`
	Version                            String20Type                         `xml:"Version,omitempty"`
	CostSharingOrMatchingRequirement   CostSharingOrMatchingRequirementType `xml:"CostSharingOrMatchingRequirement,omitempty"`
	ArchiveDate                        MMDDYYYYType                         `xml:"ArchiveDate,omitempty"`
	AdditionalInformationURL           String250Type                        `xml:"AdditionalInformationURL,omitempty"`
	AdditionalInformationText          String250Type                        `xml:"AdditionalInformationText,omitempty"`
	GrantorContactEmail                String130Type                        `xml:"GrantorContactEmail,omitempty"`
	GrantorContactEmailDescription     String102Type                        `xml:"GrantorContactEmailDescription,omitempty"`
	GrantorContactText                 String2500Type                       `xml:"GrantorContactText,omitempty"`
}

// May be no more than 100 items long
type String100Type string

// May be no more than 102 items long
type String102Type string

// May be no more than 130 items long
type String130Type string

// May be no more than 20 items long
type String20Type string

// May be no more than 2500 items long
type String2500Type string

// May be no more than 250 items long
type String250Type string

// May be no more than 4000 items long
type String4000Type string

// May be no more than 255 items long
type StringMin1Max255Type string

// Must match the pattern [^\s].{0,254}
type StringWithoutNewLine255Type string
