# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
  # Dependabot can't inspect nested directories so we need to list all local modules individually.
  # TODO: Consider switching to Rennovate.
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/gost_api"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/gost_website"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/gost_postgres"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/scheduled_ecs_task"
    schedule:
      interval: "daily"
