# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:npm]'
  - package-ecosystem: pip
    directory: /arpa-exporter
    schedule:
      interval: daily
      time: "03:00"
      timezone: America/New_York
    commit-message:
      prefix: 'Chore [deps:pip]'
    groups:
      boto3:
        # Update boto3 and boto3-stubs in the same pull request
        patterns:
          - boto3
          - boto3-stubs
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:github-actions]'
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:terraform]'
    ignore:
      - dependency-name: cloudposse/*
      - dependency-name: terraform-aws-modules/*
  # Dependabot can't inspect nested directories so we need to list all local modules individually.
  # TODO: Consider switching to Rennovate.
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/gost_api"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:terraform]'
    ignore:
      # These should be un-ignored if/when the Terraform AWS provider is updated to a more recent version
      - dependency-name: cloudposse/*
      - dependency-name: terraform-aws-modules/*
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/gost_consume_grants"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:terraform]'
    ignore:
      - dependency-name: cloudposse/*
      - dependency-name: terraform-aws-modules/*
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/gost_website"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:terraform]'
    ignore:
      - dependency-name: cloudposse/*
      - dependency-name: terraform-aws-modules/*
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/gost_postgres"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:terraform]'
    ignore:
      - dependency-name: cloudposse/*
      - dependency-name: terraform-aws-modules/*
  - package-ecosystem: "terraform"
    directory: "/terraform/modules/scheduled_ecs_task"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: 'Chore [deps:terraform]'
