/* eslint-disable func-names */

// This file was generated by generate_arpa_table_migrations.js on 2022-08-22T07:02:02.209Z.
// Describe any manual modifications below:
//  - (none)

exports.up = function (knex) {
    return knex.schema.raw(
        // This SQL generated with the following command:
        // pg_dump postgresql://localhost:5432/usdr_arpa_reporter --schema-only --no-owner --no-privileges --table=arpa_subrecipients
        `
            --
            -- PostgreSQL database dump
            --
            
            -- Dumped from database version 14.2
            -- Dumped by pg_dump version 14.2
            
            SET statement_timeout = 0;
            SET lock_timeout = 0;
            SET idle_in_transaction_session_timeout = 0;
            SET client_encoding = 'UTF8';
            SET standard_conforming_strings = on;
            -- Line below commented out by generate_arpa_table_migrations.js because it interferes with Knex
            -- SELECT pg_catalog.set_config('search_path', '', false);
            SET check_function_bodies = false;
            SET xmloption = content;
            SET client_min_messages = warning;
            SET row_security = off;
            
            SET default_tablespace = '';
            
            SET default_table_access_method = heap;
            
            --
            -- Name: arpa_subrecipients; Type: TABLE; Schema: public; Owner: -
            --
            
            CREATE TABLE public.arpa_subrecipients (
                id integer NOT NULL,
                tenant_id integer NOT NULL,
                created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at timestamp with time zone,
                updated_by integer,
                uei character varying(255),
                tin character varying(255),
                record text,
                upload_id uuid
            );
            
            
            --
            -- Name: arpa_subrecipients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
            --
            
            CREATE SEQUENCE public.arpa_subrecipients_id_seq
                AS integer
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1;
            
            
            --
            -- Name: arpa_subrecipients_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
            --
            
            ALTER SEQUENCE public.arpa_subrecipients_id_seq OWNED BY public.arpa_subrecipients.id;
            
            
            --
            -- Name: arpa_subrecipients id; Type: DEFAULT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.arpa_subrecipients ALTER COLUMN id SET DEFAULT nextval('public.arpa_subrecipients_id_seq'::regclass);
            
            
            --
            -- Name: arpa_subrecipients arpa_subrecipients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.arpa_subrecipients
                ADD CONSTRAINT arpa_subrecipients_pkey PRIMARY KEY (id);
            
            
            --
            -- Name: arpa_subrecipients arpa_subrecipients_tenant_id_tin_unique; Type: CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.arpa_subrecipients
                ADD CONSTRAINT arpa_subrecipients_tenant_id_tin_unique UNIQUE (tenant_id, tin);
            
            
            --
            -- Name: arpa_subrecipients arpa_subrecipients_tenant_id_uei_unique; Type: CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.arpa_subrecipients
                ADD CONSTRAINT arpa_subrecipients_tenant_id_uei_unique UNIQUE (tenant_id, uei);
            
            
            --
            -- Name: arpa_subrecipients arpa_subrecipients_updated_by_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.arpa_subrecipients
                ADD CONSTRAINT arpa_subrecipients_updated_by_foreign FOREIGN KEY (updated_by) REFERENCES public.users(id);
            
            
            --
            -- Name: arpa_subrecipients arpa_subrecipients_upload_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.arpa_subrecipients
                ADD CONSTRAINT arpa_subrecipients_upload_id_foreign FOREIGN KEY (upload_id) REFERENCES public.uploads(id) ON DELETE CASCADE;
            
            
            --
            -- PostgreSQL database dump complete
            --
        `,
    );
};

exports.down = function (knex) {
    return knex.schema.dropTable('arpa_subrecipients');
};
