/* eslint-disable func-names */

// This file was generated by generate_arpa_table_migrations.js on 2022-08-22T07:02:02.209Z.
// Describe any manual modifications below:
//  - (none)

exports.up = function (knex) {
    return knex.schema.raw(
        // This SQL generated with the following command:
        // pg_dump postgresql://localhost:5432/usdr_arpa_reporter --schema-only --no-owner --no-privileges --table=application_settings
        `
            --
            -- PostgreSQL database dump
            --
            
            -- Dumped from database version 14.2
            -- Dumped by pg_dump version 14.2
            
            SET statement_timeout = 0;
            SET lock_timeout = 0;
            SET idle_in_transaction_session_timeout = 0;
            SET client_encoding = 'UTF8';
            SET standard_conforming_strings = on;
            -- Line below commented out by generate_arpa_table_migrations.js because it interferes with Knex
            -- SELECT pg_catalog.set_config('search_path', '', false);
            SET check_function_bodies = false;
            SET xmloption = content;
            SET client_min_messages = warning;
            SET row_security = off;
            
            SET default_tablespace = '';
            
            SET default_table_access_method = heap;
            
            --
            -- Name: application_settings; Type: TABLE; Schema: public; Owner: -
            --
            
            CREATE TABLE public.application_settings (
                title text,
                current_reporting_period_id integer,
                duns_number text,
                validation_rule_tags text[],
                tenant_id integer NOT NULL
            );
            
            
            --
            -- Name: application_settings application_settings_current_reporting_period_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.application_settings
                ADD CONSTRAINT application_settings_current_reporting_period_id_foreign FOREIGN KEY (current_reporting_period_id) REFERENCES public.reporting_periods(id);
            
            
            --
            -- PostgreSQL database dump complete
            --
        `
    );
};

exports.down = function (knex) {
    return knex.schema.dropTable('application_settings');
};
