/* eslint-disable func-names */

// This file was generated by generate_arpa_table_migrations.js on 2022-08-22T07:02:02.209Z.
// Describe any manual modifications below:
//  - (none)

exports.up = function (knex) {
    return knex.schema.raw(
        // This SQL generated with the following command:
        // pg_dump postgresql://localhost:5432/usdr_arpa_reporter --schema-only --no-owner --no-privileges --table=reporting_periods
        `
            --
            -- PostgreSQL database dump
            --
            
            -- Dumped from database version 14.2
            -- Dumped by pg_dump version 14.2
            
            SET statement_timeout = 0;
            SET lock_timeout = 0;
            SET idle_in_transaction_session_timeout = 0;
            SET client_encoding = 'UTF8';
            SET standard_conforming_strings = on;
            -- Line below commented out by generate_arpa_table_migrations.js because it interferes with Knex
            -- SELECT pg_catalog.set_config('search_path', '', false);
            SET check_function_bodies = false;
            SET xmloption = content;
            SET client_min_messages = warning;
            SET row_security = off;
            
            SET default_tablespace = '';
            
            SET default_table_access_method = heap;
            
            --
            -- Name: reporting_periods; Type: TABLE; Schema: public; Owner: -
            --
            
            CREATE TABLE public.reporting_periods (
                id integer NOT NULL,
                name text NOT NULL,
                start_date date NOT NULL,
                end_date date NOT NULL,
                certified_at timestamp with time zone,
                certified_by integer,
                tenant_id integer NOT NULL,
                template_filename character varying(255)
            );
            
            
            --
            -- Name: reporting_periods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
            --
            
            CREATE SEQUENCE public.reporting_periods_id_seq
                AS integer
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1;
            
            
            --
            -- Name: reporting_periods_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
            --
            
            ALTER SEQUENCE public.reporting_periods_id_seq OWNED BY public.reporting_periods.id;
            
            
            --
            -- Name: reporting_periods id; Type: DEFAULT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.reporting_periods ALTER COLUMN id SET DEFAULT nextval('public.reporting_periods_id_seq'::regclass);
            
            
            --
            -- Name: reporting_periods reporting_periods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.reporting_periods
                ADD CONSTRAINT reporting_periods_pkey PRIMARY KEY (id);
            
            
            --
            -- Name: reporting_periods reporting_periods_tenant_id_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.reporting_periods
                ADD CONSTRAINT reporting_periods_tenant_id_name_unique UNIQUE (tenant_id, name);
            
            
            --
            -- Name: reporting_periods reporting_periods_certified_by_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.reporting_periods
                ADD CONSTRAINT reporting_periods_certified_by_foreign FOREIGN KEY (certified_by) REFERENCES public.users(id);
            
            
            --
            -- PostgreSQL database dump complete
            --
        `,
    );
};

exports.down = function (knex) {
    return knex.schema.dropTable('reporting_periods');
};
