/* eslint-disable func-names */

// This file was generated by generate_arpa_table_migrations.js on 2022-08-22T07:02:02.209Z.
// Describe any manual modifications below:
//  - (none)

exports.up = function (knex) {
    return knex.schema.raw(
        // This SQL generated with the following command:
        // pg_dump postgresql://localhost:5432/usdr_arpa_reporter --schema-only --no-owner --no-privileges --table=period_summaries
        `
            --
            -- PostgreSQL database dump
            --
            
            -- Dumped from database version 14.2
            -- Dumped by pg_dump version 14.2
            
            SET statement_timeout = 0;
            SET lock_timeout = 0;
            SET idle_in_transaction_session_timeout = 0;
            SET client_encoding = 'UTF8';
            SET standard_conforming_strings = on;
            -- Line below commented out by generate_arpa_table_migrations.js because it interferes with Knex
            -- SELECT pg_catalog.set_config('search_path', '', false);
            SET check_function_bodies = false;
            SET xmloption = content;
            SET client_min_messages = warning;
            SET row_security = off;
            
            SET default_tablespace = '';
            
            SET default_table_access_method = heap;
            
            --
            -- Name: period_summaries; Type: TABLE; Schema: public; Owner: -
            --
            
            CREATE TABLE public.period_summaries (
                id integer NOT NULL,
                reporting_period_id integer NOT NULL,
                project_code text NOT NULL,
                award_type text NOT NULL,
                award_number text NOT NULL,
                current_obligation numeric(19,2) NOT NULL,
                current_expenditure numeric(19,2) NOT NULL,
                award_amount numeric(19,2),
                tenant_id integer NOT NULL
            );
            
            
            --
            -- Name: period_summaries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
            --
            
            CREATE SEQUENCE public.period_summaries_id_seq
                AS integer
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1;
            
            
            --
            -- Name: period_summaries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
            --
            
            ALTER SEQUENCE public.period_summaries_id_seq OWNED BY public.period_summaries.id;
            
            
            --
            -- Name: period_summaries id; Type: DEFAULT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.period_summaries ALTER COLUMN id SET DEFAULT nextval('public.period_summaries_id_seq'::regclass);
            
            
            --
            -- Name: period_summaries period_summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.period_summaries
                ADD CONSTRAINT period_summaries_pkey PRIMARY KEY (id);
            
            
            --
            -- Name: period_summaries period_summaries_reporting_period_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.period_summaries
                ADD CONSTRAINT period_summaries_reporting_period_id_foreign FOREIGN KEY (reporting_period_id) REFERENCES public.reporting_periods(id);
            
            
            --
            -- Name: period_summaries period_summaries_tenant_id_project_code_foreign; Type: FK CONSTRAINT; Schema: public; Owner: -
            --
            
            ALTER TABLE ONLY public.period_summaries
                ADD CONSTRAINT period_summaries_tenant_id_project_code_foreign FOREIGN KEY (tenant_id, project_code) REFERENCES public.projects(tenant_id, code);
            
            
            --
            -- PostgreSQL database dump complete
            --
        `,
    );
};

exports.down = function (knex) {
    return knex.schema.dropTable('period_summaries');
};
