const agencies = require('./agencies');
const interestedCodes = require('./interestedCodes');

const usdr = agencies.find((a) => a.abbreviation === 'USDR').id;
const nevada = agencies.find((a) => a.abbreviation === 'NV').id;
const asd = agencies.find((a) => a.abbreviation === 'ASD').id;

function joinDateComponents(theDateTime, options, separator) {
    function format(m) {
        const f = new Intl.DateTimeFormat('en', m);
        let part = f.format(theDateTime);
        if (part.length === 1) {
            part = `0${part}`;
        }
        return part;
    }
    return options.map(format).join(separator);
}

function daysAhead(days) {
    const options = [{ year: 'numeric' }, { month: 'numeric' }, { day: 'numeric' }];
    const theDate = new Date();
    theDate.setDate(theDate.getDate() + days);
    return joinDateComponents(theDate, options, '-');
}

function interestedId(codeName) {
    return interestedCodes.filter((code) => code.name === codeName)[0].id;
}

const grants = [
    {
        status: 'inbox',
        grant_id: '335255',
        grant_number: '21-605',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'EAR Postdoctoral Fellowships',
        cfda_list: '47.050',
        open_date: '2021-08-11',
        close_date: '2021-11-03',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p class="MsoNormal">The Division of Earth Sciences (EAR) awards Postdoctoral Fellowships </p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ST',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '335255',
                number: '21-605',
                title: 'EAR Postdoctoral Fellowships',
                description: '<p class="MsoNormal">The Division of Earth Sciences (EAR) awards Postdoctoral Fellowships </p>',
                milestones: {
                    post_date: '2021-08-11',
                    close: {
                        date: '2021-11-03',
                    },
                },
                category: { code: 'D', name: 'Discretionary' },
            },
            agency: { code: 'NSF' },
            award: { ceiling: '6500' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [
                { code: '25' },
            ],
            funding_activity: {
                categories: [
                    {
                        name: 'Science and Technology and Other Research and Development',
                        code: 'ST',
                    },
                ],
            },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '333816',
        grant_number: 'HHS-2021-IHS-TPI-0001',
        agency_code: 'HHS-IHS',
        award_ceiling: '500000',
        cost_sharing: 'No',
        title: 'Community Health Aide Program:  Tribal Planning & Implementation',
        cfda_list: '93.382',
        open_date: '2021-08-05',
        close_date: '2021-09-06',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: ' <p>Health Aide Program for Covid</p>',
        eligibility_codes: '11 07 25',
        funding_activity_category_codes: 'HL ISS',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '333816',
                number: 'HHS-2021-IHS-TPI-0001',
                title: 'Community Health Aide Program:  Tribal Planning & Implementation',
                description: ' <p>Health Aide Program for Covid</p>',
                milestones: {
                    post_date: '2021-08-05',
                },
                category: { code: 'D', name: 'Discretionary' },
            },
            agency: { code: 'HHS-IHS' },
            award: { ceiling: '500000' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['93.382'],
            eligible_applicants: [
                { code: '11' }, { code: '07' }, { code: '25' },
            ],
            funding_activity: {
                categories: [
                    {
                        name: 'Health',
                        code: 'HL',
                    },
                    {
                        name: 'Income Security and Social Services',
                        code: 'ISS',
                    },
                ],
            },
            revision: { id: 'c3' },
        },
        created_at: '2021-08-06 16:03:53.57025-07',
        updated_at: '2021-08-11 12:35:42.562-07',
        revision_id: 'c3',
    },
    {
        status: 'inbox',
        grant_id: '666999',
        grant_number: 'grant-number-666999',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666999',
        cfda_list: '47.050',
        open_date: '2021-09-04',
        close_date: daysAhead(2),
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666999</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'HL',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666999',
                number: 'grant-number-666999',
                title: 'Test Grant 666999',
                description: '<p>Test Grant Description 666999</p>',
                milestones: {
                    post_date: '2021-09-04',
                    close: {
                        date: daysAhead(2),
                    },
                },
                category: { code: 'D', name: 'Discretionary' },
            },
            agency: { code: 'NSF' },
            award: { ceiling: '6500' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [
                { code: '25' },
            ],
            funding_activity: {
                categories: [
                    { name: 'Health', code: 'HL' },
                ],
            },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '0',
        grant_number: '0',
        agency_code: 'HHS-IHS',
        award_ceiling: '500000',
        cost_sharing: 'No',
        title: 'Test Grant 0',
        cfda_list: '93.382',
        open_date: '2021-08-05',
        close_date: daysAhead(3),
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '',
        eligibility_codes: '',
        funding_activity_category_codes: 'HL',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '0',
                number: '0',
                title: 'Test Grant 0',
                description: '',
                milestones: {
                    post_date: '2021-08-05',
                    close: {
                        date: daysAhead(3),
                    },
                },
                category: { code: 'D', name: 'Discretionary' },
            },
            agency: { code: 'HHS-IHS' },
            award: { ceiling: '500000' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['93.382'],
            eligible_applicants: [
            ],
            funding_activity: {
                categories: [
                    { name: 'Health', code: 'HL' },
                ],
            },
        },
        created_at: '2021-08-06 16:03:53.57025-07',
        updated_at: '2021-08-11 12:35:42.562-07',
    },
    {
        status: 'inbox',
        grant_id: '333333',
        grant_number: 'HHS-2021-IHS-TPI-0002',
        agency_code: 'HHS-IHS',
        award_ceiling: '500000',
        cost_sharing: 'No',
        title: 'Community Health Aide Program:  County Planning & Implementation',
        cfda_list: '93.382',
        open_date: '2021-08-05',
        close_date: daysAhead(4),
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: ' <p>Health Aide Program for Covid</p>',
        eligibility_codes: '11 07 25',
        funding_activity_category_codes: 'O',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '333333',
                number: 'HHS-2021-IHS-TPI-0002',
                title: 'Community Health Aide Program:  County Planning & Implementation',
                description: ' <p>Health Aide Program for Covid</p>',
                milestones: {
                    post_date: '2021-08-05',
                    close: {
                        date: daysAhead(4),
                    },
                },
                category: { code: 'D', name: 'Discretionary' },
            },
            agency: { code: 'HHS-IHS' },
            award: { ceiling: '500000' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['93.382'],
            eligible_applicants: [
                { code: '11' }, { code: '07' }, { code: '25' },
            ],
            funding_activity: {
                categories: [
                    { name: 'Other', code: 'O' },
                ],
            },
        },
        created_at: '2021-08-06 16:03:53.57025-07',
        updated_at: '2021-08-11 12:35:42.562-07',
    },
    {
        status: 'inbox',
        grant_id: '666666',
        grant_number: 'grant-number-666666',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666666',
        cfda_list: '47.050',
        open_date: '2021-08-11',
        close_date: daysAhead(6),
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666666</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ENV',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666666',
                number: 'grant-number-666666',
                title: 'Test Grant 666666',
                description: '<p>Test Grant Description 666666</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-11', close: { date: daysAhead(6) } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'ENV', name: 'Environment' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666656',
        grant_number: 'grant-number-666656',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666656',
        cfda_list: '47.050',
        open_date: '2021-08-12',
        close_date: daysAhead(5),
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666656</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ST',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666656',
                number: 'grant-number-666656',
                title: 'Test Grant 666656',
                description: '<p>Test Grant Description 666656</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-12', close: { date: daysAhead(5) } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: {
                categories: [{
                    code: 'ST',
                    name: 'Science and Technology and Other Research and Development',
                }],
            },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666646',
        grant_number: 'grant-number-666646',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666646',
        cfda_list: '47.050',
        open_date: '2021-08-13',
        close_date: '2021-11-01',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666646</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ISS',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666646',
                number: 'grant-number-666646',
                title: 'Test Grant 666646',
                description: '<p>Test Grant Description 666646</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-13', close: { date: '2021-11-01' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'ISS', name: 'Income Security and Social Services' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666636',
        grant_number: 'grant-number-666636',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666636',
        cfda_list: '47.050',
        open_date: '2021-08-14',
        close_date: daysAhead(6),
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666636</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'O',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666636',
                number: 'grant-number-666636',
                title: 'Test Grant 666636',
                description: '<p>Test Grant Description 666636</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-14', close: { date: daysAhead(6) } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'O', name: 'Other' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666626',
        grant_number: 'grant-number-666626',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666626',
        cfda_list: '47.050',
        open_date: '2021-08-15',
        close_date: '2021-10-30',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666626</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'AR',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666626',
                number: 'grant-number-666626',
                title: 'Test Grant 666626',
                description: '<p>Test Grant Description 666626</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-15', close: { date: '2021-10-30' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'AR', name: 'Arts' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666616',
        grant_number: 'grant-number-666616',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666616',
        cfda_list: '47.050',
        open_date: '2021-08-16',
        close_date: '2021-10-29',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666616</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'AG',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666616',
                number: 'grant-number-666616',
                title: 'Test Grant 666616',
                description: '<p>Test Grant Description 666616</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-16', close: { date: '2021-10-29' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'AG', name: 'Agriculture' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666606',
        grant_number: 'grant-number-666606',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666606',
        cfda_list: '47.050',
        open_date: '2021-08-17',
        close_date: '2021-10-28',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666606</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ISS',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666606',
                number: 'grant-number-666606',
                title: 'Test Grant 666606',
                description: '<p>Test Grant Description 666606</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-17', close: { date: '2021-10-28' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'ISS', name: 'Income Security and Social Services' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666596',
        grant_number: 'grant-number-666596',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666596',
        cfda_list: '47.050',
        open_date: '2021-08-18',
        close_date: '2021-10-27',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666596</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: '',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666596',
                number: 'grant-number-666596',
                title: 'Test Grant 666596',
                description: '<p>Test Grant Description 666596</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-18', close: { date: '2021-10-27' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666586',
        grant_number: 'grant-number-666586',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666586',
        cfda_list: '47.050',
        open_date: '2021-08-19',
        close_date: '2021-10-26',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666586</p>',
        eligibility_codes: '25',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666586',
                number: 'grant-number-666586',
                title: 'Test Grant 666586',
                description: '<p>Test Grant Description 666586</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-19', close: { date: '2021-10-26' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666576',
        grant_number: 'grant-number-666576',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666576',
        cfda_list: '47.050',
        open_date: '2021-08-20',
        close_date: '2021-10-25',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666576</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'NR',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666576',
                number: 'grant-number-666576',
                title: 'Test Grant 666576',
                description: '<p>Test Grant Description 666576</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-20', close: { date: '2021-10-25' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'NR', name: 'Natural Resources' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666566',
        grant_number: 'grant-number-666566',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666566',
        cfda_list: '47.050',
        open_date: '2021-08-21',
        close_date: '2021-10-24',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666566</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'HL',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666566',
                number: 'grant-number-666566',
                title: 'Test Grant 666566',
                description: '<p>Test Grant Description 666566</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-21', close: { date: '2021-10-24' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'HL', name: 'Health' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666556',
        grant_number: 'grant-number-666556',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666556',
        cfda_list: '47.050',
        open_date: '2021-08-22',
        close_date: '2021-10-23',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666556</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'O',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666556',
                number: 'grant-number-666556',
                title: 'Test Grant 666556',
                description: '<p>Test Grant Description 666556</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-22', close: { date: '2021-10-23' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'O', name: 'Other' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666546',
        grant_number: 'grant-number-666546',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666546',
        cfda_list: '47.050',
        open_date: '2021-08-23',
        close_date: '2021-10-22',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666546</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'NR',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666546',
                number: 'grant-number-666546',
                title: 'Test Grant 666546',
                description: '<p>Test Grant Description 666546</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-23', close: { date: '2021-10-22' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'NR', name: 'Natural Resources' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666536',
        grant_number: 'grant-number-666536',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666536',
        cfda_list: '47.050',
        open_date: '2021-08-24',
        close_date: '2021-10-21',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666536</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ED ELT EN IS ST',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666536',
                number: 'grant-number-666536',
                title: 'Test Grant 666536',
                description: '<p>Test Grant Description 666536</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-24', close: { date: '2021-10-21' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: {
                categories: [{ code: 'ED', name: 'Education' }, {
                    code: 'ELT',
                    name: 'Employment, Labor and Training',
                }, { code: 'EN', name: 'Energy' }, {
                    code: 'IS',
                    name: 'Information and Statistics',
                }, {
                    code: 'ST',
                    name: 'Science and Technology and Other Research and Development',
                }],
            },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666526',
        grant_number: 'grant-number-666526',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666526',
        cfda_list: '47.050',
        open_date: '2021-08-25',
        close_date: '2021-10-20',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666526</p>',
        eligibility_codes: '25',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666526',
                number: 'grant-number-666526',
                title: 'Test Grant 666526',
                description: '<p>Test Grant Description 666526</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-25', close: { date: '2021-10-20' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666516',
        grant_number: 'grant-number-666516',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666516',
        cfda_list: '47.050',
        open_date: '2021-08-26',
        close_date: '2021-10-19',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666516</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'HL',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666516',
                number: 'grant-number-666516',
                title: 'Test Grant 666516',
                description: '<p>Test Grant Description 666516</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-26', close: { date: '2021-10-19' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'HL', name: 'Health' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666506',
        grant_number: 'grant-number-666506',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666506',
        cfda_list: '47.050',
        open_date: '2021-08-27',
        close_date: '2021-10-18',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666506</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'HL',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666506',
                number: 'grant-number-666506',
                title: 'Test Grant 666506',
                description: '<p>Test Grant Description 666506</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-27', close: { date: '2021-10-18' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'HL', name: 'Health' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666496',
        grant_number: 'grant-number-666496',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666496',
        cfda_list: '47.050',
        open_date: '2021-08-28',
        close_date: '2021-10-17',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666496</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'O',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666496',
                number: 'grant-number-666496',
                title: 'Test Grant 666496',
                description: '<p>Test Grant Description 666496</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-28', close: { date: '2021-10-17' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'O', name: 'Other' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666486',
        grant_number: 'grant-number-666486',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666486',
        cfda_list: '47.050',
        open_date: '2021-08-29',
        close_date: '2021-10-16',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666486</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ENV',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666486',
                number: 'grant-number-666486',
                title: 'Test Grant 666486',
                description: '<p>Test Grant Description 666486</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-29', close: { date: '2021-10-16' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'ENV', name: 'Environment' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666476',
        grant_number: 'grant-number-666476',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666476',
        cfda_list: '47.050',
        open_date: '2021-08-30',
        close_date: '2021-10-15',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666476</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ISS',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666476',
                number: 'grant-number-666476',
                title: 'Test Grant 666476',
                description: '<p>Test Grant Description 666476</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-30', close: { date: '2021-10-15' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'ISS', name: 'Income Security and Social Services' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666466',
        grant_number: 'grant-number-666466',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666466',
        cfda_list: '47.050',
        open_date: '2021-08-31',
        close_date: '2021-10-14',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666466</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ED',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666466',
                number: 'grant-number-666466',
                title: 'Test Grant 666466',
                description: '<p>Test Grant Description 666466</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-08-31', close: { date: '2021-10-14' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'ED', name: 'Education' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666456',
        grant_number: 'grant-number-666456',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666456',
        cfda_list: '47.050',
        open_date: '2021-09-01',
        close_date: '2021-10-13',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666456</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ED ELT',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666456',
                number: 'grant-number-666456',
                title: 'Test Grant 666456',
                description: '<p>Test Grant Description 666456</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-09-01', close: { date: '2021-10-13' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: {
                categories: [{ code: 'ED', name: 'Education' }, {
                    code: 'ELT',
                    name: 'Employment, Labor and Training',
                }],
            },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666446',
        grant_number: 'grant-number-666446',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666446',
        cfda_list: '47.050',
        open_date: '2021-09-02',
        close_date: '2021-10-12',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666446</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'ST',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666446',
                number: 'grant-number-666446',
                title: 'Test Grant 666446',
                description: '<p>Test Grant Description 666446</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-09-02', close: { date: '2021-10-12' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: {
                categories: [{
                    code: 'ST',
                    name: 'Science and Technology and Other Research and Development',
                }],
            },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666436',
        grant_number: 'grant-number-666436',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666436',
        cfda_list: '47.050',
        open_date: '2021-09-03',
        close_date: '2021-10-11',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666436</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'O',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666436',
                number: 'grant-number-666436',
                title: 'Test Grant 666436',
                description: '<p>Test Grant Description 666436</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-09-03', close: { date: '2021-10-11' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'O', name: 'Other' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666426',
        grant_number: 'grant-number-666426',
        agency_code: 'NSF',
        award_ceiling: '6500',
        cost_sharing: 'No',
        title: 'Test Grant 666426',
        cfda_list: '47.050',
        open_date: '2021-09-04',
        close_date: '2021-10-10',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666426</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'O',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666426',
                number: 'grant-number-666426',
                title: 'Test Grant 666426',
                description: '<p>Test Grant Description 666426</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-09-04', close: { date: '2021-10-10' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'O', name: 'Other' }] },
            award: { ceiling: '6500' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666427',
        grant_number: 'grant-number-666427',
        agency_code: 'NSF',
        award_ceiling: '0',
        cost_sharing: 'No',
        title: 'Test Grant 666427',
        cfda_list: '47.050',
        open_date: '2021-09-04',
        close_date: '2023-10-20',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666427 - zero ceil</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'O',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666427',
                number: 'grant-number-666427',
                title: 'Test Grant 666427',
                description: '<p>Test Grant Description 666427 - zero ceil</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-09-04', close: { date: '2023-10-20' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'O', name: 'Other' }] },
            award: { ceiling: '0' },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
    {
        status: 'inbox',
        grant_id: '666428',
        grant_number: 'grant-number-666428',
        agency_code: 'NSF',
        award_ceiling: null,
        cost_sharing: 'No',
        title: 'Test Grant 666428',
        cfda_list: '47.050',
        open_date: '2021-09-04',
        close_date: '2023-10-20',
        notes: 'auto-inserted by script',
        search_terms: '[in title/desc]+',
        reviewer_name: 'none',
        opportunity_category: 'Discretionary',
        description: '<p>Test Grant Description 666428 - null ceil</p>',
        eligibility_codes: '25',
        funding_activity_category_codes: 'HL',
        opportunity_status: 'posted',
        raw_body_json: {
            opportunity: {
                id: '666428',
                number: 'grant-number-666428',
                title: 'Test Grant 666428',
                description: '<p>Test Grant Description 666428 - null ceil</p>',
                category: { name: 'Discretionary' },
                milestones: { post_date: '2021-09-04', close: { date: '2023-10-20' } },
            },
            agency: { code: 'NSF' },
            cost_sharing_or_matching_requirement: false,
            cfda_numbers: ['47.050'],
            eligible_applicants: [{ code: '25' }],
            funding_activity: { categories: [{ code: 'HL', name: 'Health' }] },
            award: { ceiling: null },
        },
        created_at: '2021-08-11 11:30:38.89828-07',
        updated_at: '2021-08-11 12:30:39.531-07',
    },
];

const assignedGrantsAgency = [
    {
        grant_id: grants[0].grant_id,
        agency_id: usdr,
        assigned_by: 1,
    },
    {
        grant_id: grants[0].grant_id,
        agency_id: asd,
        assigned_by: 13,
    },
    {
        grant_id: grants[0].grant_id,
        agency_id: nevada,
        assigned_by: 7,
    },
    {
        grant_id: grants[1].grant_id,
        agency_id: nevada,
        assigned_by: 6,
    },
];

const grantsInterested = [
    {
        grant_id: grants[0].grant_id,
        agency_id: usdr,
        user_id: 1,
    },
    {
        grant_id: grants[0].grant_id,
        agency_id: asd,
        user_id: 2,
    },
    {
        grant_id: grants[0].grant_id,
        agency_id: nevada,
        user_id: 2,
    },
    {
        grant_id: grants[1].grant_id,
        agency_id: nevada,
    },
    {
        grant_id: grants[2].grant_id,
        agency_id: usdr,
        user_id: 1,
        created_at: daysAhead(2),
        updated_at: daysAhead(2),
        interested_code_id: interestedId('Will Apply'),
    },
    {
        grant_id: grants[4].grant_id,
        agency_id: usdr,
        user_id: 1,
        created_at: daysAhead(4),
        updated_at: daysAhead(4),
        interested_code_id: interestedId('Will Apply'),
    },
    {
        grant_id: grants[5].grant_id,
        agency_id: usdr,
        user_id: 1,
        created_at: daysAhead(5),
        updated_at: daysAhead(5),
        interested_code_id: interestedId('Will Support'),
    },
    {
        grant_id: grants[6].grant_id,
        agency_id: usdr,
        user_id: 1,
        created_at: daysAhead(6),
        updated_at: daysAhead(6),
        interested_code_id: interestedId('Will Support'),
    },
];

module.exports = {
    grants,
    assignedGrantsAgency,
    grantsInterested,
};
