name: User Story 2
description: File an issue for a new feature
title: "[STORY]: "
projects: "Grants Team Agile Planning"
assignees:
  - usdr-grants
labels: ["story"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
    validations:
      required: false
  - type: textarea
    id: user-story
    attributes:
      label: Full User Story
      description: User can be a partner persona or USDR admin role
      placeholder: Add content here!
      value: "As a… I want to… So I can…"
    validations:
      required: true
  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Explain any current behavior
      placeholder: Add current state here! If this is a net-new feature, then say feature does not exist.
      value: "When user visits X page..."
    validations:
      required: true
 - type: textarea
    id: context
    attributes:
      label: Why is this issue important?
      description: Provide any additional context and/or business rationale for why this work is needed
      placeholder: Add context here!
      value: "This work is important because…"
    validations:
      required: true
  - type: textarea
    id: code-plan
    attributes:
      label: Relevant Code Snippets
      description: If you have any implementation ideas please add the code here. This will be pre-formatted.
      render: shell
    validations:
      required: false
