const billOptions = [
  'All Bills',
  'Bipartisan Safer Communities Act',
  'Consumer Product Safety Commission',
  'Coronavirus',
  'Corporation for National and Community Service',
  'Denali Commission',
  'Department of Agriculture',
  'Department of Commerce',
  'Department of Defense',
  'Department of Education',
  'Department of Energy',
  'Department of Health and Human Services',
  'Department of Homeland Security',
  'Department of Housing and Urban Development',
  'Department of Justice',
  'Department of Labor',
  'Department of the Interior',
  'Department of the Treasury',
  'Department of Transportation',
  'Department of Veterans Affairs',
  'Environmental Protection Agency',
  'Inflation Reduction Act',
  'Infrastructure Investment and Jobs Act',
  'Library of Congress',
  'National Aeronautics & Space Administration',
  'National Archives & Records Administration',
  'National Council on Disability',
  'National Foundation on the Arts and the Humanities',
  'National Science Foundation',
  'Nuclear Regulatory Commission',
  'Office of National Drug Control Policy',
  'Small Business Administration',
  'Social Security Administration',
];

module.exports = {
  billOptions,
};
