const billOptions = [
  'Department of Justice',
  'Department of Energy',
  'Department of the Treasury',
  '12.005',
  'Department of Health and Human Services',
  'Department of Defense',
  'Denali Commission',
  'Bipartisan Safer Communities Act',
  'National Aeronautics & Space Administration',
  'Department of Labor',
  'Department of Housing and Urban Development',
  'Department of Transportation',
  'Infrastructure Investment and jobs Act',
  'Corporation for National and Community Service',
  'Department of the Interior',
  'National Foundation on the Arts and the Humanities',
  'Department of Homeland Security',
  'National Archives & Records Administration',
  'Environmental Protection Agency',
  'Infrastructure Investment and Jobs Act',
  'Coronavirus',
  'Department of Agriculture',
  'Consumer Product Safety Commission',
  'Infrastructure Investment and Jobs Act (IIJA)',
  'Small Business Administration',
  'Office of National Drug Control Policy',
  'Department of Education',
  'National Council on Disability',
  'Nuclear Regulatory Commission',
  'Social Security Administration',
  'Department of Veterans Affairs',
  'National Science Foundation',
  'Library of Congress',
  'Office of National Drug Control Policy',
  'Department of Commerce',
  'Inflation Reduction Act',
];

module.exports = {
  billOptions,
};
