const assert = require('assert');

const { generateReport, generateSubaward, generateProjectBaseline } = require('../../../../src/arpa_reporter/services/generate-arpa-report');
const { withTenantId } = require('../helpers/with-tenant-id');
const { getTemplate } = require('../../../../src/arpa_reporter/services/get-template');

describe('arpa report generation', () => {
    it('generates a report', async () => {
        const tenantId = 0;
        const report = await withTenantId(tenantId, () => generateReport(1));
        assert.ok(report);
    });
    it('generates all the columns of subawardBulkUpload correctly', async () => {
        // tests the  generateSubaward function
        const sampleRecords = [
            {
                type: 'cover',
                upload: {
                    filename: 'ARPA SFRF Reporting Workbook _10.15errortest.xlsm',
                    created_at: '2025-01-03T14:46:09.069Z',
                    reporting_period_id: 64,
                    user_id: 4,
                    agency_id: 0,
                    validated_at: '2025-01-03T14:46:10.180Z',
                    validated_by: 4,
                    ec_code: '2.2',
                    tenant_id: 1,
                    id: 'c93c6251-c1e0-49ab-8f04-d7cc9e1ac22b',
                    notes: null,
                    invalidated_at: null,
                    invalidated_by: null,
                    created_by: 'asridhar@usdigitalresponse.org',
                    agency_code: 'USDR',
                },
                content: {
                    'Upload ID': '',
                    'Expenditure Category Group': '2-Negative Economic Impacts',
                    'Detailed Expenditure Category': '2.2-Household Assistance: Rent, Mortgage, and Utility Aid',
                },
            },
            {
                type: 'logic',
                upload: {
                    filename: 'ARPA SFRF Reporting Workbook _10.15errortest.xlsm',
                    created_at: '2025-01-03T14:46:09.069Z',
                    reporting_period_id: 64,
                    user_id: 4,
                    agency_id: 0,
                    validated_at: '2025-01-03T14:46:10.180Z',
                    validated_by: 4,
                    ec_code: '2.2',
                    tenant_id: 1,
                    id: 'c93c6251-c1e0-49ab-8f04-d7cc9e1ac22b',
                    notes: null,
                    invalidated_at: null,
                    invalidated_by: null,
                    created_by: 'asridhar@usdigitalresponse.org',
                    agency_code: 'USDR',
                },
                content: { version: 'v:20240823' },
            },
            {
                type: 'awards50k',
                subcategory: '7.1-Administrative Expenses',
                upload: {
                    filename: '24Q4 7.1.xlsm',
                    created_at: '2025-01-21T20:55:14.883Z',
                    reporting_period_id: 64,
                    user_id: 4,
                    agency_id: 0,
                    validated_at: '2025-01-21T20:55:16.369Z',
                    validated_by: 4,
                    ec_code: '7.1',
                    tenant_id: 1,
                    id: 'ff4d3f49-e6a0-4229-848b-c6899790e2f1',
                    notes: null,
                    invalidated_at: null,
                    invalidated_by: null,
                    created_by: 'asridhar@usdigitalresponse.org',
                    agency_code: 'USDR',
                },
                content: {
                    Recipient_UEI__c: 'TVXXX123XXX9',
                    __rowNum__: 12,
                    Recipient_EIN__c: '200999888',
                    Entity_Type_2__c: 'Contractor',
                    Project_Identification_Number__c: 'X999X999888111',
                    Award_No__c: 'C725V523000171',
                    Award_Type__c: 'Contract: Purchase Order',
                    Award_Amount__c: 213888,
                    Award_Date__c: '2023-01-03T00:00:00.000Z',
                    Period_of_Performance_Start__c: '2023-01-03T00:00:00.000Z',
                    Period_of_Performance_End__c: '2024-12-31T00:00:00.000Z',
                    Place_of_Performance_Address_1__c: '1 Main St.',
                    Place_of_Performance_City__c: 'New York',
                    State_Abbreviated__c: 'NY',
                    Place_of_Performance_Zip__c: '10001',
                    Description__c: 'Project Support Services',
                    Subaward_Changed__c: 'No',
                    Contract_Estimated_Expended: 0,
                    Personnel_Cost_Estimates__c: 'Yes',
                    Personnel_Estimated_Expended: 1232593.0499999998,
                    Personnel_Expended_FTE_Count: 31,
                    Contract_Expended_Justification: 'Each project budget includes non-arpa capital funding to ensure that all schedule requirements for obligations and expenditures are met.',
                },
            },
        ];
        const result = await generateSubaward(sampleRecords);
        // assert that the result is equal to []
        const expectedResult = [
            [
                null,
                'TVXXX123XXX9',
                '200999888',
                'X999X999888111',
                'C725V523000171',
                'Contractor',
                'Contract: Purchase Order',
                '213888',
                '2023-01-03T00:00:00.000Z',
                undefined,
                undefined,
                '2023-01-03T00:00:00.000Z',
                '2024-12-31T00:00:00.000Z',
                '1 Main St.',
                undefined,
                undefined,
                'New York',
                'NY',
                '10001',
                undefined,
                undefined,
                'Project Support Services',
                undefined,
                undefined,
                undefined,
                undefined,
                'Yes',
                1232593.0499999998,
                31,
                undefined,
                0,
                'Each project budget includes non-arpa capital funding to ensure that all schedule requirements for obligations and expenditures are met.',
            ],
        ];
        const subawardBulkUploadTemplate = await getTemplate('subawardBulkUpload');

        assert.equal(JSON.stringify(result), JSON.stringify(expectedResult));

        // verifies that the latest treasury output template has the same amount of columns as the funciton output
        assert.equal(result[0].length, subawardBulkUploadTemplate[3].length);
    });
    it('generates all the columns of projectBaselineBulkUpload correctly', async () => {
        const records = [
            {
                type: 'ec7',
                subcategory: '7.1-Administrative Expenses',
                upload: {
                    filename: '24Q4 7.1.xlsm',
                    created_at: '2025-01-21T20:55:14.883Z',
                    reporting_period_id: 64,
                    user_id: 4,
                    agency_id: 0,
                    validated_at: '2025-01-21T20:55:16.369Z',
                    validated_by: 4,
                    ec_code: '7.1',
                    tenant_id: 1,
                    id: 'ff4d3f49-e6a0-4229-848b-c6899790e2f1',
                    notes: null,
                    invalidated_at: null,
                    invalidated_by: null,
                    created_by: 'asridhar@usdigitalresponse.org',
                    agency_code: 'USDR',
                },
                content: {
                    Name: 'Audit - Trails',
                    __rowNum__: 20,
                    Project_Identification_Number__c: 'X725X5XXXXX71',
                    Completion_Status__c: 'Completed less than 50%',
                    Adopted_Budget__c: 4562.61,
                    Total_Obligations__c: 4562.61,
                    Total_Expenditures__c: 0,
                    Current_Period_Obligations__c: 4562.61,
                    Current_Period_Expenditures__c: 0,
                    Project_Description__c: 'State audit costs for the administration of ARPA funds for Trails projects.',
                    Project_Start_Date__c: '2023-01-01T00:00:00.000Z',
                },
            },
            {
                type: 'ec7',
                subcategory: '7.3-Costs Associated with Satisfying Certain Legal and Administrative Requirements of the SLFRF Program After December 31, 2024',
                upload: {
                    filename: '24Q4 7.1.xlsm',
                    created_at: '2025-01-21T20:55:14.883Z',
                    reporting_period_id: 64,
                    user_id: 4,
                    agency_id: 0,
                    validated_at: '2025-01-21T20:55:16.369Z',
                    validated_by: 4,
                    ec_code: '7.1',
                    tenant_id: 1,
                    id: 'ff4d3f49-e6a0-4229-848b-c6899790e2f1',
                    notes: null,
                    invalidated_at: null,
                    invalidated_by: null,
                    created_by: 'asridhar@usdigitalresponse.org',
                    agency_code: 'USDR',
                },
                content: {
                    Name: 'Test 7.3',
                    __rowNum__: 21,
                    Project_Identification_Number__c: 'X725X6XXXXX71',
                    Completion_Status__c: 'Completed less than 50%',
                    Adopted_Budget__c: 5609.47,
                    Total_Obligations__c: 5609.47,
                    Total_Expenditures__c: 0,
                    Current_Period_Obligations__c: 5609.47,
                    Current_Period_Expenditures__c: 0,
                    Project_Description__c: 'State audit costs for the adminstration of SLFRF funds.',
                    Project_Start_Date__c: '2023-01-01T00:00:00.000Z',
                    Admin_Estimated_Expended__c: 35,
                    Admin_Actual_Expended__c: 77,
                    Admin_Expended_Description__c: 'Test admin expended description',
                    Admin_Expended_Justification__c: 'Test admin expended justification',
                },
            },
        ];
        const expectedResult = [
            [
                null,
                "7-Administrative",
                "7.1-Administrative Expenses",
                "Audit - Trails",
                "X725X5XXXXX71",
                "Completed less than 50%",
                null,
                "2023-01-01T00:00:00.000Z",
                null,
                "4562.61",
                "4562.61",
                "0",
                "4562.61",
                "0",
                null,
                null,
                null,
                null,
                null,
                "State audit costs for the administration of ARPA funds for Trails projects.",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
            ],
            [
                null,
                "7-Administrative",
                "7.3-Costs Associated with Satisfying Certain Legal and Administrative Requirements of the SLFRF Program After December 31, 2024",
                "Test 7.3",
                "X725X6XXXXX71",
                "Completed less than 50%",
                null,
                "2023-01-01T00:00:00.000Z",
                null,
                "5609.47",
                "5609.47",
                "0",
                "5609.47",
                "0",
                null,
                null,
                null,
                null,
                null,
                "State audit costs for the adminstration of SLFRF funds.",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                35,
                77,
                "Test admin expended description",
                "Test admin expended justification",
            ],
        ];
        const result = await generateProjectBaseline(records);
        const projectBaselineBulkUploadTemplate = await getTemplate('projectBaselineBulkUploadTemplate');
        assert.equal(JSON.stringify(result), JSON.stringify(expectedResult));
        assert.equal(result[0].length, projectBaselineBulkUploadTemplate[3].length);
    });
});

// NOTE: This file was copied from tests/server/services/generate-arpa-report.spec.js (git @ ada8bfdc98) in the arpa-reporter repo on 2022-09-23T20:05:47.735Z
